### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by apetrichkovich** [atom/electron-quick-start#15]
My page is like that (left & right arrows are not shown):
html
head
head
body
script src="js/common/jquery-2.1.4.min.js"/script
script src="js/common/bootstrap.min.js"/script
body
html

npm install && npm start - starts blank page with console error (Uncaught Error: Bootstrap's JavaScript requires jQuery).

To make page work you need to have jquery script both in head & body tags what is strage.

**Comment by jlord** [comment]
This doesn't appear to be a bug in the `quick-start-repository` itself as it doesn't use jQuery or Bootstrap. 

If you are still having this issue you may try opening an issue on the Electron repo or double check that you are pointing to the right places for the libraries you're using :+1:
