### ISSUE TITLE
Resource loading doesn't work

### ISSUE THREAD

**Issue by apetrichkovich** [atom/electron-quick-start#16]
I'm using Javascript library for loading and using message resource property files:
https://github.com/suhaibkhan/messageResource.js

Page works in browser, but not as electron desktop app.

**Comment by apetrichkovich** [comment]
Resource location is resources/messages.properties.

**Comment by jlord** [comment]
This repository is just for the quick start app, it looks like you're troubleshooting problems with Electron itself. If you're still having trouble try opening (or searching for similar) issues there: [atom/electron](http://github.com/atom/electron).
