### ISSUE TITLE
Example app doesn't exit on OS X

### ISSUE THREAD

**Issue by noseglid** [atom/electron-quick-start#17]
Shoudn't [`!= 'darwin'`](https://github.com/atom/electron-quick-start/blob/master/main.js#L17) really be `== 'darwin'` ?

**Comment by santiq** [comment]
Read the comment above that line of code

`app.on('window-all-closed', function() {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform != 'darwin') {
    app.quit();
  }
});`

On OS X it is common for applications and their menu bar **to stay active until the user quits explicitly with Cmd + Q**

**Comment by jlord** [comment]
Yep, ditto @santiq, this is mirroring the native behavior on OS X.

**Comment by jlord** [comment]
@noseglid we opened #26 to create a more expected OS X behavior of being able to restore the app once all the windows are closed by clicking the doc icon.

**Comment by noseglid** [comment]
I must admit i misunderstood the comment. I've always hated this behavior in OS X and i just assumed Electron was trying to mitigate it, not simulate it :). My bad. Thanks for response
