### ISSUE TITLE
loadURL(`file://${__dirname}/index.html`) doesn't work

### ISSUE THREAD

**Issue by icoxfog417** [atom/electron-quick-start#18]
`loadURL(`file://${__dirname}/index.html`)` doesn't work at least my environment (Windows7, node:5.1.1, electron: 0.35.4).

I think it should be `loadURL('file://' + __dirname + '/index.html')` according to the [Quick Start](http://electron.atom.io/docs/latest/tutorial/quick-start/).

**Comment by koalaylj** [comment]
although this works well on my computer(mac, Node 4.1.1, Chrome 45.0.2454.85, Electron 0.35.4.).
```javascript
  mainWindow.loadURL(`file://${__dirname}/index.html`);
```
but i think @icoxfog417  is right . never see  ` in javascript.

**Comment by saiberz** [comment]
@koalaylj it's es6 notation

**Comment by jlord** [comment]
Yep, the tick and `${}` are ES6, which work in Electron because they're supported by V8. I'm not sure why it's not working on your machine, but the syntax doesn't do much for us here so I'm fine to go back to the way it was (and is written in the doc) :thumbsup:

**Comment by harmandeep-singh** [comment]
Hi,
i am new for electron writing very first program on window 10 - 64 bit OS , i am facing same problem
 
this line is not working 
win.loadURL('file://${__dirname}/index.html')

when i copy the source from GIT and noticed this char ` notation and it's working , 
i am not understanding why single quotes or double quotes working that am trying to writing them with hands instead of copy 

this is working (i copy it from quick start guide)
win.loadURL(`file://${__dirname}/index.html`)

may be mac or windows charset diff. this does not making sense to me.. 

here is console error : 
Not allowed to load local resource: file://%24%7B__dirname%7D/index.html

i thought its fixed in long back ago  not sure about it

Thank you :)

**Comment by harmandeep-singh** [comment]
Many Thanks i found this is working for me 
win.loadURL('file://' + __dirname + '/index.html');
hopefully will helps the other too 

sorry ! am new :) 
Thank you.

**Comment by chandan2545855** [comment]
mainWindow.loadURL(`file://${__dirname}/index.html`);
and 
win.loadURL('file://' + __dirname + '/index.html');
did not work for me and i tried the below code which worked:
mainwin.loadURL(url.format({
        pathname:path.join(__dirname,'index.html'),
        protocol:'file:'
    }));

**Comment by TheEmrio** [comment]
@chandan2545855 Thank you a lot!

**Comment by coreilabs** [comment]
`'file://' + __dirname + '/index.html'`
all ok here with w7

**Comment by phil294** [comment]
You are confusing something here. It should be ```loadURL(`file://${__dirname}/index.html`)```. These are backticks, not single quotes.

**Comment by SCHQ** [comment]
If we want to use ${} format in the string, we need to use the "`" to quto the strings, not qutos.

**Comment by newcanopies** [comment]
Does the index.html have to be in the same directory as electron's main.js ?

loading HTML from same dir as main.js does work
`mainWindow.loadFile('index.html')`

but loading from a neighboring directory does not:
`mainWindow.loadURL(`file://${__dirname}../outsidedirectory/http/client/index.html`)`

**What would be the way to load from another dir:**

/project
     app_dir/main.js
     http_dir/content/index.html
                             /css
                             /js


here's the full Main.js:
<details>
```
require('dotenv').config();

const setupEvents = require('../electron/installers/setupEvents')
if (setupEvents.handleSquirrelEvent()) {
  return;
}

const electron = require('electron');
console.log(require.resolve('electron'))
const app = electron.app;
const {ipcMain} = require('electron');
var path = require('path')
require('../electron/dialog/dialog')

// native browser window
const BrowserWindow = electron.BrowserWindow

let mainWindow
let secondWindow

function createWindow () {

  mainWindow = new BrowserWindow({titleBarStyle: 'hidden',
    width: 1281,
    height: 800,
    minWidth: 1281,
    minHeight: 800,
    backgroundColor: '#312450',
    show: false,
    icon: path.join(__dirname, '../electron/icons/png/64x64.png'),
    webPreferences: {
      nodeIntegration: true
    }
  })

  //TROUBLESHOOT ES6 notation
  // load the index.html of the app.
/**
  mainWindow.loadURL(`file://${__dirname}gzweb/http/client/index.html`)
  mainWindow.loadFile('index.html')
*/

  mainWindow.once('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.on('closed', function () {
    mainWindow = null
  })

  secondWindow = new BrowserWindow({frame: false,
    width: 800,
    height: 600,
    minWidth: 800,
    minHeight: 600,
    backgroundColor: '#312450',
    show: false,
    icon: path.join(__dirname, '../electron/icons/png/64x64.png'),
    parent: mainWindow,
    webPreferences: {
      nodeIntegration: true
    }
  })

  secondWindow.loadURL(`file://${__dirname}../electron/windows/ipcwindow.html`)

  require('../electron/menu/mainmenu.js')
}


ipcMain.on('open-second-window', (event, arg)=> {
    secondWindow.show()
})

ipcMain.on('close-second-window', (event, arg)=> {
    secondWindow.hide()
})

app.on('ready', createWindow)


app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

```
</details>
