### ISSUE TITLE
Error using new api electron

### ISSUE THREAD

**Issue by saiberz** [atom/electron-quick-start#21]
When i try to run ```npm start``` after ```npm install``` i get this error: 
```
App threw an error when running [TypeError: Cannot read property 'start' of undefined]
````
but if i change main.js to old api  it works perfectly
```
/* const electron = require('electron'); */
const app = require('app');  // Module to control application life.
const BrowserWindow = require('browser-window');  // Module to create native browser window.
```
so i'm not sure if this new api works only for some node versions

**Comment by jlord** [comment]
Not sure exactly what happened here but today we removed the only thing calling `start` in #25 so it shouldn't happen again :+1:

**Comment by saiberz** [comment]
@jlord thanks, i forgot to close this issue, i found the problem here: https://github.com/atom/electron/issues/3708
