### ISSUE TITLE
Use latest instead of specific version

### ISSUE THREAD

**Issue by johnmuhl** [atom/electron-quick-start#22]
Replace  `devDependencies['electron-prebuilt'] = 'x.x.x'` in `package.json` with `devDependencies['electron-prebuilt'] = 'latest'`. This way there will be no need to update `package.json` after every Electron release.

**Comment by jlord** [comment]
There are a couple of issues with doing this that I raise [here](https://github.com/atom/electron-quick-start/pull/23#issuecomment-165206750) so we're gonna stick with using version numbers. Thanks!
