### ISSUE TITLE
Quick Start does not run - Linux Mint

### ISSUE THREAD

**Issue by aplatypus** [atom/electron-quick-start#33]
Just tonight, I cloned the Quick-Start project and it plain got an error when the _**main**_ script started.

I didn't poke around too much, as I figured you want to know when a __quick start__ isn't starting.  Anyway happy to report or peek at settings if the cause is not obvious.

Thanks in advance, ... _platypus_

###  command replay
I was following the steps from the project readme:

      # Clone this repository
      $ git clone https://github.com/atom/electron-quick-start
      Cloning into 'electron-quick-start'...
      remote: Counting objects: 101, done.
      remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
      Receiving objects: 100% (101/101), 16.06 KiB | 0 bytes/s, done.
      Resolving deltas: 100% (49/49), done.
      Checking connectivity... done.

      # Go into the repository
      $  cd electron-quick-start
      $ pwd
       ~/sandbox/tmp/electron-quick-start

       # Install dependencies and run the app
       $ npm install && npm start
     
_**result**_

      > electron-quick-start@1.0.0 start /mnt/data/home/projects/sandbox/tmp/electron-quick-start
      > electron main.js
      
      fs.js:439
        return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                       ^
      Error: ENOENT, no such file or directory '/mnt/data/home/projects/sandbox/tmp/electron-quick-start/node_modules/electron-prebuilt/path.txt'
          at Object.fs.openSync (fs.js:439:18)
          at Object.fs.readFileSync (fs.js:290:15)
          at Object.<anonymous> (/mnt/data/home/projects/sandbox/tmp/electron-quick-start/node_modules      /electron-prebuilt/index.js:4:42)
          at Module._compile (module.js:456:26)
          at Object.Module._extensions..js (module.js:474:10)
          at Module.load (module.js:356:32)
          at Function.Module._load (module.js:312:12)
          at Module.require (module.js:364:17)
          at require (module.js:380:17)
          at Object.<anonymous> (/mnt/data/home/projects/sandbox/tmp/electron-quick-start/node_modules      /electron-prebuilt/cli.js:3:16)
      
      npm ERR! Linux 3.19.0-32-generic
      npm ERR! argv "node" "/usr/bin/npm" "start"
      npm ERR! node v0.10.42
      npm ERR! npm  v2.14.19
      npm ERR! code ELIFECYCLE
      npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
      npm ERR! Exit status 8
      npm ERR! 
      npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
      npm ERR! This is most likely a problem with the electron-quick-start package,
      npm ERR! not with npm itself.
      npm ERR! Tell the author that this fails on your system:
      npm ERR!     electron main.js
      npm ERR! You can get information on how to open an issue for this project with:
      npm ERR!     npm bugs electron-quick-start
      npm ERR! Or if that isn't available, you can get their info via:
      npm ERR! 
      npm ERR!     npm owner ls electron-quick-start
      npm ERR! There is likely additional logging output above.
      
      npm ERR! Please include the following file with any support request:
      npm ERR!     /mnt/data/home/projects/sandbox/tmp/electron-quick-start/npm-debug.log
 
### Version info
*  git:  v1.9.1
* node:  v0.10.42
* npm:  2.14.19
* electron: 0.4.1
* linux:  v 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

------------
##  debug log

       0 info it worked if it ends with ok
       1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
       2 info using npm@2.14.19
       3 info using node@v0.10.42
       4 verbose node symlink /usr/bin/node
       5 verbose run-script [ 'prestart', 'start', 'poststart' ]
       6 info prestart electron-quick-start@1.0.0
       7 info start electron-quick-start@1.0.0
       8 verbose unsafe-perm in lifecycle true
       9 info electron-quick-start@1.0.0 Failed to exec start script
       10 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
       10 verbose stack Exit status 8
       10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
       10 verbose stack     at EventEmitter.emit (events.js:98:17)
       10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
       10 verbose stack     at ChildProcess.emit (events.js:98:17)
       10 verbose stack     at maybeClose (child_process.js:766:16)
       10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
       11 verbose pkgid electron-quick-start@1.0.0
       12 verbose cwd /mnt/data/home/projects/sandbox/tmp/electron-quick-start
       13 error Linux 3.19.0-32-generic
       14 error argv "node" "/usr/bin/npm" "start"
       15 error node v0.10.42
       16 error npm  v2.14.19
       17 error code ELIFECYCLE
       18 error electron-quick-start@1.0.0 start: `electron main.js`
       18 error **Exit status 8**
       19 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
       19 error This is most likely a problem with the electron-quick-start package,
       19 error not with npm itself.
       19 error Tell the author that this fails on your system:
       19 error     electron main.js
       19 error You can get information on how to open an issue for this project with:
       19 error     npm bugs electron-quick-start
       19 error Or if that isn't available, you can get their info via:
       19 error
       19 error     npm owner ls electron-quick-start
       19 error There is likely additional logging output above.
       20 verbose exit [ 1, true ]

**Comment by jlord** [comment]
Hmmm. Did the dependencies download without error? Are you able to run `electron .` in that directory?

I'm not sure if its a part of this but the version of Node you have is fairly old. You say you're using Electron `v0.4.1` but with this app it should be using Electron `v0.36.x` no matter what because it's a dependency.

**Comment by carltongibson** [comment]
I'm seeing this exact same issue on OS X

**Comment by jlord** [comment]
@carltongibson I am not able to recreate the issue on OS X. Could you help by answering the same questions mentioned above:

- Does `npm install` complete without error?
- Are you able to run `electron .` inside of the `electron-quick-start` directory?
- What version of OS X and Node are you using?

**Comment by jlord** [comment]
Also, @carltongibson and @aplatypus would you mind re-installing `electron-prebuilt` and trying again (I'm wanting to make sure that it is getting installed correctly, re: https://github.com/mafintosh/electron-prebuilt/issues/85).

```bash
cd electron-quick-start
npm install electron-prebuilt@0.36.8
# then when install completes successfully 
electron .
```

**Comment by carltongibson** [comment]
OK, updating node **and** nuking `node_modules` and reinstalling fixed it for me. Thanks for the help.

**Comment by jlord** [comment]
@carltongibson awesome! 

@aplatypus Hopefully this works for you as well, if it doesn't, please re-open.

**Comment by ervine** [comment]
Indeed it's a network problem, download the module incompletely.
In China, [taobao Mirrors](https://npm.taobao.org/) is recommended.

**Comment by makohisa** [comment]
I resolved same problem with below command.
      npm install electron-packager
