### ISSUE TITLE
Minor mistake on "Get started with Electron"

### ISSUE THREAD

**Issue by gimenete** [atom/electron-quick-start#5]
The README tells you to run `npm install && npm start` which is correct. But in the [website](http://electron.atom.io) it says `npm install && npm run` which is not correct (run vs start).

I tried to find the `gh-pages` branch for the website but I'm afraid it is not published in a github repository so I just came here and opened an issue :)

**Comment by jlord** [comment]
Whoops, thanks for catching this and for future reference the website has its own repository: https://github.com/atom/electron.atom.io. Closing out here since the fix will happen there 👍

**Comment by jlord** [comment]
🔗 https://github.com/atom/electron.atom.io/commit/ca6866da2ff700a07c5735843740d989ca293e10

**Comment by bluskies** [comment]
Okay. Thanks for all the information you have been sendinge "Jessica Lord"

Terrie Hales
LMAO

**Comment by bluskies** [comment]
Lol. Its so funny. He has his and I have one too
So happen to be I was there with mine. Look rral close.
