### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by deejross** [atom/electron-quick-start#6]
After checking out this repository and running: npm install, I'm getting the following error message:

```
Error: self signed certificate in certificate chain
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.34.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.34.2 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
```

I am running behind a corporate firewall that does MITM HTTP/HTTPS content filtering, which does inject its own certificate. However, I don't normally get this error when installing NPM packages, as I have the self-signed certificate marked as trusted on my machine, and I've also set the "cafile=/path/to/cert" and "strict-ssl=false" set in my ~/.npmrc file.

**Comment by kevinsawicki** [comment]
I believe this is an issue with https://github.com/mafintosh/electron-prebuilt

Would you mind reopening the issue there?

**Comment by jlord** [comment]
Closing here, see issue on `electron-prebuilt` :point_up:
